name: donationsapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  firebase_core: ^2.14.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1


flutter:


  uses-material-design: true
